### PR TITLE
Fix URL resource loading 

### PR DESCRIPTION
**Pull request by vimpagliazzo**
for cases like a resource in located in a jar file

We use jetty embedded as container and we setup manually the resource location to be into jar files (new PathResource(new URL(JarResource.newJarResource(new PathResource(uiURL))))

It later however fail traying to load resources. The offending code is in the HtmlTreeBuilder class where a URL is always converted to be a File. The proposed patch uses url.openStream instead and solves the issue.

### CODE REVIEW

**Comment by vimpagliazzo** [comment]
I am sorry I could not create an issue in the tracker, but logging in with forum credential seems to not be working for me.

**Comment by DevChu** [comment]
This commit seems reasonable but I am wondering how to reproduce your case. Could you provide more details? Thanks.

**Comment by vimpagliazzo** [comment]
I have uploaded a test case here: https://github.com/vimpagliazzo/zk-loader-testcase

You would have to download, do a "mvn install" on the root project, then "cd zk-loader-runner" and run mvn exec:java -Dexec.mainClass="Runner"  to see the error. Hope it helps.

**Comment by DevChu** [comment]
I created an issue here : http://tracker.zkoss.org/browse/ZK-3123

**Pull request closed without merging**
