### PR TITLE
ZK-4182: zul.inp.Errorbox is shown regardless the component visibility

### PR DESCRIPTION
**Pull request by scribetw**

### CODE REVIEW

**Comment by plijyfes** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I could not fetch the latest changes from GitHub. Please try again in a few minutes.

**Comment by plijyfes** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Pull request merged**
