### PR TITLE
ZK-3870: wrong theme css class at body element

### PR DESCRIPTION
**Pull request by scribetw**

### CODE REVIEW

**Comment by scribetw** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Comment by klyvechen** [comment]
@zkadmin rebase?

**Comment by klyvechen** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I could not fetch the latest changes from GitHub. Please try again in a few minutes.

**Comment by klyvechen** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I could not checkout B85-ZK-3870 locally.

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Comment by DevChu** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Pull request merged**
