### PR TITLE
add an improvement : view model can be proxy

### PR DESCRIPTION
**Pull request by aruille31**
ProxyUtils : utility class use to access to the target class of a proxy
AbstractAnnotatedMethodInvoker + BinderImpl + CommandBindingImpl : get
the target class
ParamCall + BenELResolver : invoke a method from a proxy

### CODE REVIEW

**Comment by jumperchen** [comment]
any test case?

**Comment by aruille31** [comment]
when I have time I will send you a test.
I tested on an existing application

Best regards

Antoine RUILLE

Analyste développeur

05 32 11 05 12

0 820 420 337

www.synox-group.com


[http://www.synox-group.com/sites/default/files/signature/logo-signature.jpg]<www.synox-group.com>


[http://www.synox-group.com/sites/default/files/signature/fb.jpg]<https://www.facebook.com/SynoxGroup>[http://www.synox-group.com/sites/default/files/signature/twitter.jpg]<https://twitter.com/SynoxLive>[http://www.synox-group.com/sites/default/files/signature/viadeo.jpg]<http://fr.viadeo.com/fr/company/synox-group>

[http://www.synox-group.com/sites/default/files/signature/gif-signature.gif]<www.synox-group.com>


De : Jumper Chen [mailto:notifications@github.com]
Envoyé : jeudi 23 avril 2015 12:40
À : zkoss/zk
Cc : Antoine Ruille
Objet : [!! Mail en masse]Re: [zk] add an improvement : view model can be proxy (#287)


any test case?

**Comment by aruille31** [comment]
Hi,

i would like to use zktest but i have some issues...

missing these maven dependencies 
org.zkoss.zk:zkex:${project.version}
org.zkoss.zk:zkmax:${project.version}
org.zkoss.zk:zuti:${project.version}

${project.version} => 8.0.0-SNAPSHOT

I probably missed something for build this project with maven.

help please.

Regards,

Antoine

**Comment by scribetw** [comment]
Closed stale PR.

**Pull request closed without merging**
