### PR TITLE
ZK-3883:The Grid/Listbox header and context are misaligned after resized

### PR DESCRIPTION
**Pull request by plijyfes**

### CODE REVIEW

**Comment by charlesqqq** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Comment by charlesqqq** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Pull request merged**
