### PR TITLE
ZK-3906: colorbox not initializing hex value in palette popup

### PR DESCRIPTION
**Pull request by scribetw**

### CODE REVIEW

**Comment by scribetw** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Comment by scribetw** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I could not add remote: https://github.com/zkoss/zk.git.

**Comment by scribetw** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Comment by scribetw** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Comment by DevChu** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Pull request merged**
