### PR TITLE
ZK-4159: listbox (mold="select") re-renders after first au response

### PR DESCRIPTION
**Pull request by scribetw**

### CODE REVIEW

**Comment by charlesqqq** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I could not fetch the latest changes from GitHub. Please try again in a few minutes.

**Comment by scribetw** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I could not fetch the latest changes from GitHub. Please try again in a few minutes.

**Pull request merged**
