### PR TITLE
ZK-4661: Portallayout dragging position miscalculated sometimes

### PR DESCRIPTION
**Pull request by plijyfes**

### CODE REVIEW

**Review by scribetw — APPROVED** [review]

**Comment by scribetw** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Review by DevChu — APPROVED** [review]

**Comment by DevChu** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Pull request merged**
