### PR TITLE
ZK-4797: Supporting Jakarta EE namespace

### PR DESCRIPTION
**Pull request by strangelookingnerd**
I was the original requester of the ticket and am currently in the process of upgrading a bigger application towards jakarta.* namespace.
During testing I patched ZK to my needs and thought it might be useful for you. 

* changed dependencies towards jakarta based counterparts
* changed imports towards jakarta.*
* include patched commons-fileupload (ouch...)

It's a very rough solution - but here goes nothing ;)

If there are any questions feel free to ping me.

### CODE REVIEW

**Comment by scribetw** [comment]
Hi strangelookingnerd,

Thanks for your contribution.
At this time being, we're still evaluating which version to migrate to.
Since it's a breaking change, we won't do it in 9.6.0 (the current developing version).

Currently, we might leave the code as-is and will use some build tools to convert class files to Jakarta EE.
And we'll have two releases in one version for both `jakarta.*` and `javax.*` in a period.

**Comment by strangelookingnerd** [comment]
Seems reasonable.
Can you give me a rough estimation when a release supporting `jakarta.*` is scheduled?

**Comment by scribetw** [comment]
We'll try releasing 2 copies of ZK 9.6.0 in Q2 2021, for both Java EE and Jakarta EE.

**Comment by scribetw** [comment]
Use mine #2490 instead.

**Pull request closed without merging**
