### PR TITLE
ZK-5223: the if element doesn't keep the position of its child component

### PR DESCRIPTION
**Pull request by DevChu**

### CODE REVIEW

**Review by jumperchen — APPROVED** [review]
@zkadmin rebase

**Review by jumperchen — APPROVED** [review]
@zkadmin rebase

**Comment by jumperchen** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Review by jumperchen — APPROVED** [review]

**Comment by jumperchen** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes and merged, enjoy!

**Pull request merged**
