### PR TITLE
ZK-3950: Accordion mold tabbox doesn't properly resize when adding or…

### PR DESCRIPTION
**Pull request by charlesqqq**
… removing items dynamically

### CODE REVIEW

**Comment by klyvechen** [comment]
@zkadmin rebase

**Comment by klyvechen** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I could not fetch the latest changes from GitHub. Please try again in a few minutes.

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Pull request merged**
