### PR TITLE
ZK-3977: ListModel listdatalistener not cleared when component is des…

### PR DESCRIPTION
**Pull request by charlesqqq**
…troyed

### CODE REVIEW

**Comment by wenninghsu** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I could not pull charlesqqq/zk from GitHub.

**Comment by scribetw** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I could not fetch the latest changes from GitHub. Please try again in a few minutes.

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Pull request merged**
