### PR TITLE
Bug Fixed ZK-4134: Chosenbox - remove interval doesn't remove the las…

### PR DESCRIPTION
**Pull request by wenninghsu**
…t selection

### CODE REVIEW

**Comment by charlesqqq** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Comment by charlesqqq** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Pull request merged**
