### PR TITLE
ZK-3989: Firefox default document-level mouseUp event sometime preven…

### PR DESCRIPTION
**Pull request by charlesqqq**
…ts selection in input

Fixed in cf42473b00696756e99af67df7f52eb45324a060

### CODE REVIEW

**Comment by DevChu** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Comment by scribetw** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Pull request merged**
