### PR TITLE
ZK-4788: setCols(0) causes exception for InputElement

### PR DESCRIPTION
**Pull request by b952426**
ZK-4788: unset default value for InputElement

### CODE REVIEW

**Review by scribetw — CHANGES_REQUESTED** [review]
setCols(0) is accepted

Keep setCols(11)

**Review by scribetw — CHANGES_REQUESTED** [review]
Not what the user want

**Review by DevChu — APPROVED** [review]

**Review by plijyfes — APPROVED** [review]

**Review by scribetw — APPROVED** [review]

**Comment by scribetw** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Comment by scribetw** [comment]
@zkadmin rebase

**Comment by zkadmin** [comment]
I just pushed up the changes, enjoy!

**Pull request merged**
